export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const NOWPLAYING_MOVIE_LIST = "NOWPLAYING_MOVIE_LIST";
export const TRENDING_MOVIE_LIST = "TRENDING_MOVIE_LIST";
export const UPCOMING_MOVIE_LIST = "UPCOMING_MOVIE_LIST";
export const POPULAR_MOVIE_LIST = "POPULAR_MOVIE_LIST";

export const DISCOVER_MOVIE_LIST = "DISCOVER_MOVIE_LIST";
export const DISCOVER_TV_LIST = "DISCOVER_TV_LIST";
export const RECOMMENDEDATION_LIST = "RECOMMENDEDATION_LIST";
export const SIMILAR_LIST = "SIMILAR_LIST";

export const ADD_TO_MY_LIST = "ADD_TO_MY_LIST";
export const GET_MY_LIST = "GET_MY_LIST";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const MOVIE_REQUEST = "MOVIE_REQUEST";
export const MOVIE_REQUEST_SUCCESS = "MOVIE_REQUEST_SUCCESS";
