export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const NOWPLAYING_MOVIE_LIST = "NOWPLAYING_MOVIE_LIST";
export const TRENDING_MOVIE_LIST = "TRENDING_MOVIE_LIST";
export const UPCOMING_MOVIE_LIST = "UPCOMING_MOVIE_LIST";
export const POPULAR_MOVIE_LIST = "POPULAR_MOVIE_LIST";

export const DISCOVER_MOVIE_LIST = "DISCOVER_MOVIE_LIST";
export const DISCOVER_TV_LIST = "DISCOVER_TV_LIST";

export const ADD_TO_CART = "ADD_TO_CART";
